export const ASSIGNEDOUTLET = {
  "": "",
  Catering: "Catering",
  "Greenbelt 1": "Greenbelt 1",
  PICC: "PICC",
  Landmark: "Landmark",
  "Head Office": "Head Office",
  Commissary: "Commissary",
  Redifeast: "Redifeast",
  Franchise: "Franchise",
  ICTSI: "ICTSI",
  "Rockwell Club": "Rockwell Club",
  "Greenbelt DB": "Greenbelt DB",
  "HO Corp": "HO Corp",
  "LM Trinoma": "LM Trinoma",
  Eastwood: "Eastwood",
  "St. Lukes": "St. Lukes",
  "Wack-Wack": "02Wack-Wack8",
  "SL - JuiceBar": "SL - JuiceBar",
  "EDSA Shangri-La": "EDSA Shangri-La",
  "Manila Golf": "Manila Golf",
  "Eastwood Express": "Eastwood Express",
  KIDZANIA: "KIDZANIA",
  "LM Alabang": "LM Alabang",
  "NAIA-T3": "NAIA-T3",
  "Ayala North Exchange": "Ayala North Exchange",
  "Celebrity Club": "Celebrity Club",
  "Araneta Gateway": "Araneta Gateway",
};

export const EMPLOYEETYPE = {
  Probationary: "Probationary",
  Regular: "Regular",
  Casual: "Casual",
  "On-Call": "On-Call",
  Supervisor: "Supervisor",
  OJT: "OJT",
  Director: "Director",
  "General Manager": "General Manager",
  "Co-Terminus": "Co-Terminus",
  "Project Based": "Project Based",
  CEO: "CEO",
};

export const DEPARTMENT = {
  Accounting: "Accounting",
  Admin: "Admin",
  Audit: "Audit",
  HRD: "HRD",
  Linen: "Linen",
  Marketing: "Marketing",
  Motorpool: "Motorpool",
  Production: "Production",
  Service: "Service",
  IT: "IT",
  Sales: "Sales",
  JJC: "JJC",
  Wares: "Wares",
  Purchasing: "Purchasing",
  Maintenance: "Maintenance",
  Express: "Express",
  Storeroom: "Storeroom",
  Freezer: "Freezer",
  "Golden Lion": "Golden Lion",
  "Cost Control": "Cost Control",
};

export const PREFIX = {
  "": "",
  Mr: "Mr.",
  Ms: "Ms.",
  Mrs: "Mrs.",
};

export const EMPSTATUS = {
  "": "",
  Active: "Y",
  Inactive: "N",
};
