export const USERLEVELS = {
  User: "User",
  Admin: "Admin",
  Approver: "Approver",
  OutletProcessor: "Outlet Processor",
  PayrollMaster: "Payroll Master",
  CostController: "Cost Controller",
  Processor: "Processor",
};

export const USERGROUPS = {
  Accounting: "Accounting",
  HRD: "HRD",
  Outlet: "Outlet",
  Audit: "Audit",
  IT: "IT",
  Marketing: "Marketing",
  Catering: "Catering",
  Sales: "Sales",
  Franchise: "Franchise",
};

export const BRANCHES = {
  Catering: "Catering",
  "Greenbelt 1": "Greenbelt 1",
  PICC: "PICC",
  Landmark: "Landmark",
  "Head Office": "Head Office",
  Commissary: "Commissary",
  Redifeast: "Redifeast",
  Franchise: "Franchise",
  ICTSI: "ICTSI",
  "Rockwell Club": "Rockwell Club",
  "Greenbelt DB": "Greenbelt DB",
  "HO Corp": "HO Corp",
  "LM Trinoma": "LM Trinoma",
  Eastwood: "Eastwood",
  "St. Lukes": "St. Lukes",
  "Wack-Wack": "Wack-Wack",
  "SL - JuiceBar": "SL - JuiceBar",
  "EDSA Shangri-La": "EDSA Shangri-La",
  "Manila Golf": "Manila Golf",
  "Eastwood Express": "Eastwood Express",
  KIDZANIA: "KIDZANIA",
  "LM Alabang": "LM Alabang",
  "NAIA-T3": "NAIA-T3",
  "Ayala North Exchange": "Ayala North Exchange",
  "Celebrity Club": "Celebrity Club",
};
