export const USERLEVELS = {
  User: "User",
  Admin: "Admin",
  HR: "HR",
  Approver: "Approver",
  Accounting: "Accounting",
  OutletProcessor: "Outlet/Processor",
  Audit: "Audit",
  PayrollMaster: "Payroll Master",
  Approver2: "Approver 2",
};

export const USERGROUPS = {
  Accounting: "Accounting",
  HRD: "HRD",
  Outlet: "Outlet",
  Audit: "Audit",
  IT: "IT",
  Administrator: "Administrator",
  HR: "HR",
  vpnOutlet: "vpn_Outlet",
  Marketing: "Marketing",
  "Catering/Cost Control": "Catering/Cost Control",
  Commissary: "Commissary",
  Catering: "Catering",
  PICC: "PICC",
  newVpnOutlet: "new_vpn_outlet",
};

export const BRANCHES = {
  Catering: "Catering",
  "Greenbelt 1": "Greenbelt 1",
  PICC: "PICC",
  Landmark: "Landmark",
  "Head Office": "Head Office",
  Commissary: "Commissary",
  Redifeast: "Redifeast",
  Franchise: "Franchise",
  ICTSI: "ICTSI",
  "Rockwell Club": "Rockwell Club",
  "Greenbelt DB": "Greenbelt DB",
  "HO Corp": "HO Corp",
  "LM Trinoma": "LM Trinoma",
  Eastwood: "Eastwood",
  "St. Lukes": "St. Lukes",
  "Wack-Wack": "Wack-Wack",
  "SL - JuiceBar": "SL - JuiceBar",
  "EDSA Shangri-La": "EDSA Shangri-La",
  "Manila Golf": "Manila Golf",
  "Eastwood Express": "Eastwood Express",
  KIDZANIA: "KIDZANIA",
  "LM Alabang": "LM Alabang",
  "NAIA-T3": "NAIA-T3",
  "Ayala North Exchange": "Ayala North Exchange",
  "Celebrity Club": "Celebrity Club",
};
